version: '3'
services:
  app:
    image: app:latest
    command: start
    ports:
      - 8000:8000
    links:
      - db
  web:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - 3306:3306
  volumes:
    php  logvolume01: {}
