version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
